### ISSUE TITLE
automount daemon unable to reconnect

### ISSUE THREAD

**Issue by gman0** [cvmfs-contrib/cvmfs-csi#121]
When the nodeplugin is restarted the automount daemon won't reconnect, leaving consumer Pods with broken mounts.

**Comment by gman0** [comment]
I'm testing a fix and if all goes well there will be a patch release still today.

**Comment by jjgraham** [comment]
Is the fix for your xix working today ??

**Comment by jjgraham** [comment]
We are still having issues loosing mounts

Should the automount-reconciler be exiting like this ?

I1015 04:43:19.815077 1951734 reconciler.go:92] Exec-ID 409: Running command env=[] prog=/usr/bin/cvmfs_talk args=[cvmfs_talk -i sdsc-nrp-osdf-origin.osgstorage.org mountpoint]
I1015 04:43:19.850240 1951734 reconciler.go:92] Exec-ID 409: Process exited: exit status 0
I1015 04:43:49.779216 1951734 reconciler.go:92] Exec-ID 410: Running command env=[] prog=/usr/bin/cvmfs_talk args=[cvmfs_talk -i cvmfs-config.cern.ch mountpoint]
I1015 04:43:49.798854 1951734 reconciler.go:92] Exec-ID 410: Process exited: exit status 0
I1015 04:43:49.798896 1951734 reconciler.go:92] Exec-ID 411: Running command env=[] prog=/usr/bin/cvmfs_talk args=[cvmfs_talk -i sdsc-nrp-osdf-origin.osgstorage.org mountpoint]
I1015 04:43:49.828030 1951734 reconciler.go:92] Exec-ID 411: Process exited: exit status 0
I1015 04:44:19.792199 1951734 reconciler.go:92] Exec-ID 412: Running command env=[] prog=/usr/bin/cvmfs_talk args=[cvmfs_talk -i cvmfs-config.cern.ch mountpoint]
I1015 04:44:19.809204 1951734 reconciler.go:92] Exec-ID 412: Process exited: exit status 0
I1015 04:44:19.809233 1951734 reconciler.go:92] Exec-ID 413: Running command env=[] prog=/usr/bin/cvmfs_talk args=[cvmfs_talk -i sdsc-nrp-osdf-origin.osgstorage.org mountpoint]
I1015 04:44:19.837880 1951734 reconciler.go:92] Exec-ID 413: Process exited: exit status 0
I1015 04:44:49.793290 1951734 reconciler.go:92] Exec-ID 414: Running command env=[] prog=/usr/bin/cvmfs_talk args=[cvmfs_talk -i cvmfs-config.cern.ch mountpoint]
I1015 04:44:49.811435 1951734 reconciler.go:92] Exec-ID 414: Process exited: exit status 0
I1015 04:44:49.811474 1951734 reconciler.go:92] Exec-ID 415: Running command env=[] prog=/usr/bin/cvmfs_talk args=[cvmfs_talk -i sdsc-nrp-osdf-origin.osgstorage.org mountpoint]
I1015 04:44:49.840007 1951734 reconciler.go:92] Exec-ID 415: Process exited: exit status 0

**Comment by gman0** [comment]
@jjgraham please open a new issue and describe the problem there, with logs attached. Thanks!
