### ISSUE TITLE
FIX: HELM values file on master branch still points to the old "magnum" registry enpoint

### ISSUE THREAD

**Issue by jtorrex** [cvmfs-contrib/cvmfs-csi#131]
Hi,

I was previously using an old release of the driver working properly on an EKS cluster.

Now I'm trying to upgrade it to the latest version (2.3.2) and I saw that the master branch points to the 'old' endpoint magnum on some references of the values.yaml file:

https://github.com/cvmfs-contrib/cvmfs-csi/blob/master/deployments/helm/cvmfs-csi/values.yaml#L72C1-L73C1
https://github.com/cvmfs-contrib/cvmfs-csi/blob/master/deployments/helm/cvmfs-csi/values.yaml#L80C52-L80C52
etc

This endpoint is not working anymore:

```
$ helm pull oci://registry.cern.ch/magnum/cvmfs-csi --version latest
Error: Unable to locate any tags in provided repository: oci://registry.cern.ch/magnum/cvmfs-csi
```
Should they need to point to the newer registry endpoint?

```
helm pull oci://registry.cern.ch/kubernetes/charts/cvmfs-csi --version 2.3.2
Pulled: registry.cern.ch/kubernetes/charts/cvmfs-csi:2.3.2
Digest: sha256:f016d4a1488705d8cddd67f7fb48caffbe564e61f1d0544cf7a33c4285a591cf
```

**Comment by jtorrex** [comment]
Created a PR on: #130

**Comment by gman0** [comment]
Done in https://github.com/cvmfs-contrib/cvmfs-csi/pull/130. Thanks for the work @jtorrex, closing.
