### ISSUE TITLE
Suggested fixes to kubernetes manifests

### ISSUE THREAD

**Issue by landerlini** [cvmfs-contrib/cvmfs-csi#132]
Hi,
  thanks for developing and sharing this great tool!

While trying it out I noticed some lines of the manifests breaking the kubectl apply.
They seem typos to me, so you may want to fix them.

 * Mixed list style (conflicting JSON and YAML formats) in [nodelugin-dameonset.yaml:119](https://github.com/cvmfs-contrib/cvmfs-csi/blob/d46443af7fdf65058af8718a972f4774108c1a0c/deployments/kubernetes/nodeplugin-daemonset.yaml#L119)
 * Empty mapping in [cvmfs-client-configmap.yaml](https://github.com/cvmfs-contrib/cvmfs-csi/blob/d46443af7fdf65058af8718a972f4774108c1a0c/deployments/kubernetes/cvmfs-client-configmap.yaml#L21)

Also, I had to modify the http proxy to "DIRECT" in the [configmap](https://github.com/cvmfs-contrib/cvmfs-csi/blob/d46443af7fdf65058af8718a972f4774108c1a0c/deployments/kubernetes/cvmfs-client-configmap.yaml#L10C23-L10C51) for running from outside CERN, but this `http://ca-proxy.cern.ch:3128` is probably intended to be the default in this repo. Maybe consider adding one more explicit line in docs. 

Thanks again!

**Comment by xkzl** [comment]
hi @landerlini 
just to mention that i am facing the same issue here and also modified `CA_HTTP_PROXY=DIRECT` and `CVMFS_USE_GEOAPI=no`

```
[10:26:17] marcomeyer@MarcoMacBook-Pro:~/Software/igwn/k8s-cvmfs-ci/cvmfs-csi $ 
$ kubectl create -f deployments/kubernetes
deployment.apps/cvmfs-csi-controllerplugin created
serviceaccount/cvmfs-csi-controllerplugin created
clusterrole.rbac.authorization.k8s.io/cvmfs-csi-controllerplugin-provisioner created
clusterrolebinding.rbac.authorization.k8s.io/cvmfs-csi-controllerplugin-provisioner created
csidriver.storage.k8s.io/cvmfs.csi.cern.ch created
configmap/cvmfs-csi-default-local created
configmap/cvmfs-csi-config-d created
error parsing deployments/kubernetes/nodeplugin-daemonset.yaml: error converting YAML to JSON: yaml: line 119: did not find expected key
[10:26:18] marcomeyer@MarcoMacBook-Pro:~/Software/igwn/k8s-cvmfs-ci/cvmfs-csi $ ✗ (last command failed) 
$ nano deployments/kubernetes/nodeplugin-daemonset.yaml
[10:26:26] marcomeyer@MarcoMacBook-Pro:~/Software/igwn/k8s-cvmfs-ci/cvmfs-csi $ 
$ nano deployments/kubernetes/nodeplugin-daemonset.yaml:119
[10:26:44] marcomeyer@MarcoMacBook-Pro:~/Software/igwn/k8s-cvmfs-ci/cvmfs-csi $ 
$ kubectl get all -l app=cvmfs-csi
NAME                                              READY   STATUS             RESTARTS   AGE
pod/cvmfs-csi-controllerplugin-75c547db95-jc22q   1/2     ImagePullBackOff   0          6m29s

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cvmfs-csi-controllerplugin   0/1     1            0           6m29s

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/cvmfs-csi-controllerplugin-75c547db95   1         1         0       6m29s
```

I don't know how to fix it, but maybe @gman0 knows

**Comment by xkzl** [comment]
https://github.com/cvmfs-contrib/cvmfs-csi/commit/e3543f0c69090fa7fcdc28a9eb543f79090169eb#diff-909fc1962e874d86125129ad5d6914abb5e8a0ff609945e0b6afad20d3e14370

**Comment by gman0** [comment]
Hello, thanks for the suggestion! Would you like to send a patch? I can do it of course, however I'm actually considering removing the `deployments/kubernetes/` directory altogether. The preferred way to deploy the driver is via the [Helm chart](https://github.com/cvmfs-contrib/cvmfs-csi/tree/master/deployments/helm/cvmfs-csi).

**Comment by landerlini** [comment]
Thanks for replying.
I agree maintaining two "copies" of the manifests, one bare the other templated,  makes little sense.
I will give a try to the helm chart.
