### ISSUE TITLE
Performance drop using CVMFS through this plugin

### ISSUE THREAD

**Issue by MohammadAliAmir** [cvmfs-contrib/cvmfs-csi#139]
Hi,

I have this plugin now installed and tried to validate performance of CVMFS on containers compared to on a virtual machine configured as client. We load modules through an Lmod setup. I see some significant performance drop when comparing the 2.
Also added the difference with the first call as cvmfs has to initially fetch before having it available in cache. 

|  command | container  |  VM  | container (first call) | VM (first call) 
|---|---|---|---|---|
|  `time ml Python` | real 0m3.957s <br/> user 0m0.787s <br/> sys 0m0.198s | real 0m0.192s <br/> user 0m0.162s <br/> sys 0m0.026s |  real 0m7.214s <br/> user 0m0.937s <br/> sys 0m0.257s |  real 0m0.439s <br/> user 0m0.406s <br/> sys 0m0.027s |
| `time uptime` | real 0m0.536s<br/>user 0m0.010s<br/>sys 0m0.058s | real 0m0.004s<br/>user 0m0.000s<br/>sys 0m0.004s  | real 0m8.991s<br/>user 0m0.020s<br/>sys 0m0.112s | real 0m0.007s<br/>user 0m0.000s<br/>sys 0m0.004s |

As you can see this is significantly slower. Usually we would be loading much more complex modules than the example one.
Configured the cvmfs plugin mainly with default settings, only added our repository config.

resources for the containers are 
```yaml
resources:
  limits:
    memory: "128Mi"
    cpu: "50m"
  requests:
    memory: "64Mi"
    cpu: "10m"
```

Is there a way to improve performance or did I perhaps misconfigure something?

**Comment by amalthundiyil** [comment]
@MohammadAliAmir Thank you for opening this issue. I've tried the resource restriction on an [example pod](https://github.com/cvmfs-contrib/cvmfs-csi/blob/master/example/pod-all-repos.yaml) and a VM, and measured the times for `ls /cvmfs/alice.cern.ch` (first call). This is what I obtained:
```
real 0m0.22s, user 0m0.00s, sys 0m0.00s # csi
real 0m0.283s, user 0m0.002s, sys 0m0.000s # vm
```

Could you please let me know how I can reproduce the commands you mentioned locally? IIUC, [`uptime`](https://linux.die.net/man/1/uptime) doesn't seem to be related to CVMFS.

**Comment by MohammadAliAmir** [comment]
Thanks for responding! `uptime` is indeed not related to cvmfs, thats why I was so confused that even non-related commands are executed slower. The other command `ml` is from [Lmod](https://lmod.readthedocs.io/en/latest/030_installing.html), a little bit more complex to set up and I don't want you to go through this entire setup. I am simply looking for clues that could indicate why this is running slower. In the meantime, I also did compare ls from a container to a vm and I see quite normal response:
```bash
real 0m0.002s user 0m0.000s sys 0m0.002s # vm
real 0m0.006s user 0m0.001s sys 0m0.004s # container
```
After loading my profile for lmod which sets some environment variables correctly to start loading modules it still looks good
```bash
real 0m0.005s user 0m0.002s sys 0m0.003s
```
Whenever I load a module effectively, the `ls` of the repo really drops in performance. I've compared them here for a vm and the container
```bash
real 0m1.686s user 0m0.013s sys 0m0.077s # container
real 0m0.035s user 0m0.001s sys 0m0.014s # vm
```

So loading a module sets alot of environment variables, which in this case many will link to a path of the cvmfs repository.

**Comment by MohammadAliAmir** [comment]
I have been monitoring the resources for the pods deployed by the daemonset, apparrently it was CPU throttling with these assigned resources. Increasing the resources (upto a core for the CPU limit) on the relevant containers (automount and automount reconciler) did resolve my slow responsiveness from the CVMFS mount. 

What I learned:
Depending on your workload, you will need to set the resources for the containers in the cvmfs-csi plugin accordingly.
