### ISSUE TITLE
Publish the Helm chart on a public registry

### ISSUE THREAD

**Issue by aledegano** [cvmfs-contrib/cvmfs-csi#149]
Hello!
The documentation recommends to install cvmfs-csi through the OCI bundle uploaded on the CERN registry.
However, as far as I can tell, the registry is only available to users with a valid CERN account (I might be wrong as I couldn't find any documentation for the registry...).
If that is indeed the case, would it be possible to push the Helm chart of `cvmfs-csi` to a public registry too? It would be pretty easy to host it in this very repo in Github too, for instance.

Thank you!

**Comment by rochaporto** [comment]
@1602077 it might make sense to move it to a public project in the CERN registry? Might be the best option, the other one is to put it under docker hub or ghcr or similar.

**Comment by 1602077** [comment]
@rochaporto cvmfs-csi gets currently written to the kubernetes project in the registry which I believe is already public.

Alessandro should be able to pull from this without needing credentials, however I don't think he will be able to log in to the harbor UI.

@aledegano Would you mind sharing the command you are running to pull / install the chart with?

Happy to look into replication to a public registry also

**Comment by aledegano** [comment]
You are right, I can pull the OCI artifact, my bad.
Closing the issue and thank you for the reply!
