### ISSUE TITLE
Move away from centos:7 base image

### ISSUE THREAD

**Issue by gman0** [cvmfs-contrib/cvmfs-csi#46]
cvmfs-csi image is based on centos:7: https://github.com/cvmfs-contrib/cvmfs-csi/blob/release-v2.0/deployments/docker/Dockerfile.

Given EOL of the distribution and it containing pretty old packages, we need to move to something newer. To make things easier, we should pick a distro where CVMFS packages are available. See https://cernvm.cern.ch/fs/ for the list.

**Comment by jcpunk** [comment]
I'd recommend the RHEL UBI images.  I've been working with the UBI team and the CVMFS dependencies should make it into the UBI repos in the next few weeks.

**Comment by gman0** [comment]
There's [cvmfs/service](https://hub.docker.com/r/cvmfs/service) minimal image we could use, but it's missing autofs-related tools. https://github.com/cvmfs/cvmfs/issues/3114 tracks that.
