### ISSUE TITLE
configMap for default.d directory

### ISSUE THREAD

**Issue by jtorrex** [cvmfs-contrib/cvmfs-csi#55]
Plugin version used: v2.0.0

On the latest release, only two configMaps are allowed, for defining **default.local** file, and **config.d** directory files.

I'm trying to setup the plugin with the need of using the parameter **CVMFS_CONFIG_REPOSITORY**.

I tried to define it on the default.local file, but running **cvmfs_config chksetup**, I'm facing this error:

```Error: CVMFS_CONFIG_REPOSITORY can only be set in /etc/cvmfs/default.conf and /etc/cvmfs/default.d/*.conf (not in /etc/cvmfs/default.local)```

**In previous versions, there is a configMap to define files inside the default.d directory.**

* Why is it the default.d configMap deprecated?
* Is there an alternative or workaround to define the parameter CVMFS_CONFIG_REPOSITORY using the default.local and config.d configMaps?
* Can be added again a configMap to map the file inside the default.d directory?

**Comment by jtorrex** [comment]
Hi @gman0, thanks for your reply and your work.

I'm currently mapping the configuration using configMaps and I find this mechanism enough simple and intuitive to "store" the proper configuration on the values.yml file, having also the capacity to track it easily on a control version such as Git/GH/GL, etc, and using it "transparently" on integrations without involving "existent" files on storage support to mount it later.

About the proposal on issue #54,  If I can decide, I would probably choose to stay on configMaps but adding some others like /etc/cvmfs/defaul.d/*, for example. Anyway, I'm conscient that keeping this mechanism requires additional work on the code to add extra configMaps if required, modifying different files.

If you are considering the volume mount approach because is more flexible, please, go ahead, you probably have a better understanding of what is better to improve the usability of the plugin, the only point that I consider that is mandatory if you decide to change to this approach, is to have a good section docu/guide explaining on how to use it properly.

Thanks again for your work, if I can help you with whatever you consider, please don't hesitate on mentioning me.

Regards!

**Comment by gman0** [comment]
Hi @jtorrex, you can check https://github.com/cvmfs-contrib/cvmfs-csi/pull/56 if that would work for you. Thanks!

**Comment by jtorrex** [comment]
Checked #56. For my particular use case, I think that we can close this issue as the new patch provides a better flexible way for mapping the desired configuration. Thanks for your work again @gman0.
