### ISSUE TITLE
Adding custom configs to extraConfigMaps

### ISSUE THREAD

**Issue by nuwang** [cvmfs-contrib/cvmfs-csi#64]
With the latest changes, extraConfigMaps is an array.
https://github.com/cvmfs-contrib/cvmfs-csi/blob/a90329e7bf6bfe1d936168d286af6219f9a36a80/deployments/helm/cvmfs-csi/values.yaml#L9

This makes it difficult to add additional configuration in a custom values file without also repeating default.local. (It can be done on the commandline, but not through a values file afaik). Making it a dict would make that use case easier I believe.

**Comment by gman0** [comment]
Hi @nuwang, thanks for the suggestion! I think we can make this change.
