### ISSUE TITLE
Cut the next release?

### ISSUE THREAD

**Issue by afgane** [cvmfs-contrib/cvmfs-csi#68]
Would it be possible to make another release with some of the recent changes that were merged? Or is there a defined timeline/milestone when a release will happen?

**Comment by gman0** [comment]
Hi @afgane, here's the milestone for the next point release: https://github.com/cvmfs-contrib/cvmfs-csi/issues?q=milestone%3A%22Release+v2.2.0%22+. There is no concrete date, but I'm aiming to include these tasks in the release.

**Comment by gman0** [comment]
Hi @afgane, FYI [v2.2.0](https://github.com/cvmfs-contrib/cvmfs-csi/releases/tag/v2.2.0) is out.
